<#@ template debug="true" hostSpecific="true" #>
<#@ output extension=".cs" #>
<#@ Assembly Name="System.Core" #>
<#@ Assembly Name="System.Windows.Forms" #>
<#@ import namespace="System" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Diagnostics" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Collections" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ include file="..\T4\T4Util.ttinclude" #>
using System;
using System.ComponentModel;

namespace LangExt
{
    /// <summary>
    /// 関数がnullを返したことを表す例外です。
    /// この例外は、Func.ToResultの結果としてのみ使用されます。
    /// </summary>
    public sealed class NullResultException : Exception
    {
        /// <summary>objがNullResultExceptionであればtrueを返します。</summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) { return obj is NullResultException; }
        /// <summary>このオブジェクトのハッシュコードを返します。</summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() { return 11; }
        /// <summary>このオブジェクトの文字列表現を返します。</summary>
        public override string ToString() { return "NullResultException"; }

        /// <summary>
        /// 使用しません。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static new bool Equals(object a, object b)
        {
            return object.Equals(a, b);
        }

        /// <summary>
        /// 使用しません。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static new bool ReferenceEquals(object a, object b)
        {
            return object.ReferenceEquals(a, b);
        }
    }

    partial class Func
    {
        /// <summary>関数の結果をResultで包む関数に変換します。</summary>
        public static Func<Result<T, Exception>> ExnToResultFunc<T>(this Func<T> self)
        {
            return () => { try { return Result.Success(self()); } catch (Exception e) { return Result.Failure(e); } };
        }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullの場合、Failureになります。</summary>
        public static Func<Result<T, Unit>> NullToResultFunc<T>(this Func<T> self) where T : class { return () => Result.Create(self()); }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullの場合、Failureになります。</summary>
        public static Func<Result<T, Unit>> NullToResultFunc<T>(this Func<T?> self) where T : struct { return () => Result.Create(self()); }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullか例外の場合、Failureになります。nullの場合はNullResultExceptionがFailureの値として使用されます。</summary>
        public static Func<Result<T, Exception>> ToResultFunc<T>(this Func<T> self)
        {
            return () =>
            {
                try
                {
                    var res = self();
                    if (res == null)
                        return Result.Failure((Exception)new NullResultException());
                    return Result.Success(res);
                } catch (Exception e) { return Result.Failure(e); }
            };
        }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullか例外の場合、Failureになります。nullの場合はNullResultExceptionがFailureの値として使用されます。</summary>
        public static Func<Result<T, Exception>> ToResultFunc<T>(this Func<T?> self)
            where T : struct
        {
            return () =>
            {
                try
                {
                    var res = self();
                    if (res == null)
                        return Result.Failure((Exception)new NullResultException());
                    return Result.Success(res.Value);
                } catch (Exception e) { return Result.Failure(e); }
            };
        }

<#
    for (int i = 1; i <= 16; i++) {
#>
        /// <summary>関数の結果をResultで包む関数に変換します。</summary>
        public static Func<<#= TypeParams("T", i) #>, Result<U, Exception>> ExnToResultFunc<<#= TypeParams("T", i) #>, U>(this Func<<#= TypeParams("T", i) #>, U> self)
        {
            return (<#= MethodCallArgs("t", i) #>) => { try { return Result.Success(self(<#= MethodCallArgs("t", i) #>)); } catch (Exception e) { return Result.Failure(e); } };
        }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullの場合、Failureになります。</summary>
        public static Func<<#= TypeParams("T", i) #>, Result<U, Unit>> NullToResultFunc<<#= TypeParams("T", i) #>, U>(this Func<<#= TypeParams("T", i) #>, U> self)
            where U : class
        {
            return (<#= MethodCallArgs("t", i) #>) => Result.Create(self(<#= MethodCallArgs("t", i) #>));
        }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullの場合、Failureになります。</summary>
        public static Func<<#= TypeParams("T", i) #>, Result<U, Unit>> NullToResultFunc<<#= TypeParams("T", i) #>, U>(this Func<<#= TypeParams("T", i) #>, U?> self)
            where U : struct
        {
            return (<#= MethodCallArgs("t", i) #>) => Result.Create(self(<#= MethodCallArgs("t", i) #>));
        }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullか例外の場合、Failureになります。nullの場合はNullResultExceptionがFailureの値として使用されます。</summary>
        public static Func<<#= TypeParams("T", i) #>, Result<U, Exception>> ToResultFunc<<#= TypeParams("T", i) #>, U>(this Func<<#= TypeParams("T", i) #>, U> self)
        {
            return (<#= MethodCallArgs("t", i) #>) =>
            {
                try
                {
                    var res = self(<#= MethodCallArgs("t", i) #>);
                    if (res == null)
                        return Result.Failure((Exception)new NullResultException());
                    return Result.Success(res);
                } catch (Exception e) { return Result.Failure(e); }
            };
        }

        /// <summary>関数の結果をResultで包む関数に変換します。関数の結果がnullか例外の場合、Failureになります。nullの場合はNullResultExceptionがFailureの値として使用されます。</summary>
        public static Func<<#= TypeParams("T", i) #>, Result<U, Exception>> ToResultFunc<<#= TypeParams("T", i) #>, U>(this Func<<#= TypeParams("T", i) #>, U?> self)
            where U : struct
        {
            return (<#= MethodCallArgs("t", i) #>) =>
            {
                try
                {
                    var res = self(<#= MethodCallArgs("t", i) #>);
                    if (res == null)
                        return Result.Failure((Exception)new NullResultException());
                    return Result.Success(res.Value);
                } catch (Exception e) { return Result.Failure(e); }
            };
        }

<# } #>
    }
}
